#!/bin/sh
set -e

mysql -u root -p"${MYSQL_ROOT_PASSWORD}" <<-EOF
CREATE DATABASE IF NOT EXISTS \`${APP_DB_NAME}\`;

CREATE USER IF NOT EXISTS '${APP_DB_USER}'@'%' IDENTIFIED BY '${APP_DB_PASSWORD}';

GRANT ALL PRIVILEGES ON \`${APP_DB_NAME}\`.* TO '${APP_DB_USER}'@'%';

FLUSH PRIVILEGES;
EOF
