name: "studyplanner"

services:
  tomcat:
    build:
      context: .
      dockerfile: ./.docker/tomcat/Dockerfile
      args:
        DB_HOST: ${DB_HOST}
        DB_USER: ${APP_DB_USER}
        DB_PASS: ${APP_DB_PASS}
        DB_NAME: ${APP_DB_NAME}
        AUTH_SECRET: ${APP_AUTH_SECRET}
    container_name: tomcat
    restart: unless-stopped
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - letsencrypt_data:/etc/letsencrypt:ro
      - ./.docker/tomcat/conf/server.xml:/usr/local/tomcat/conf/server.xml:ro
      - ./.docker/tomcat/conf/rewrite.conf:/usr/local/tomcat/conf/rewrite.conf:ro
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: unless-stopped
    expose:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./.docker/mysql/initdb.d:/docker-entrypoint-initdb.d:ro
    env_file: ./.env
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  certbot:
    image: certbot/certbot:v5.5.0
    profiles:
      - certbot
    volumes:
      - letsencrypt_data:/etc/letsencrypt

volumes:
  mysql_data:
  letsencrypt_data:
